apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: text-generation-webui-pvc
  namespace: user-zhangyh
  labels:
    app: text-generation-webui-pvc
spec:
  storageClassName: ceph-rbd
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi